package rules.reasoning;
dialect  "mvel"

import sbnz.blisskin.model.dto.*;
import sbnz.blisskin.model.enumerations.*;
import sbnz.blisskin.model.*;
import java.util.List;

declare SeriousSkinIssue
    name: String;
end

declare DrugRecommendation
    drug: Drug;
end

rule "Patient currently has eczema and/or psoriasis"
    when
        TreatmentRequest($currentSkinIssues: skinIssues)
        Number(intValue >= 1) from accumulate (
            SkinIssue(name == "Eczema" || name == "Psoriasis") from $currentSkinIssues,
            count(1)
        )
    then
        insert(new SeriousSkinIssue(drools.getRule().getName()))
end

rule "Patient currently has blackheads and/or whiteheads"
    when
        TreatmentRequest($currentSkinIssues: skinIssues)
        Number(intValue >= 1) from accumulate (
            SkinIssue(name == "Blackheads" || name == "Whiteheads") from $currentSkinIssues,
            count(1)
        )
    then
        insert(new SeriousSkinIssue(drools.getRule().getName()))
end

rule "Patient currently has acne"
    when
        TreatmentRequest($currentSkinIssues: skinIssues)
        Number(intValue >= 1) from accumulate (
            SkinIssue(name == "Acne") from $currentSkinIssues,
            count(1)
        )
    then
        insert(new SeriousSkinIssue(drools.getRule().getName()))
end

// -----------------------------------------------------------------------
rule "Recommend Antibiotics for eczema or psoriazis"
salience 3
activation-group "drug-recommendation"
    when
        /* ako postoji terapija u prethodnih 60d gde je tretiran eczema ili psoriasis */
        SeriousSkinIssue(name == "Patient currently has eczema and/or psoriasis")
        Treatment($treatedSkinIssues: treatedSkinIssues, prescriptionDrug == Drug.NONE) over window:time(60d)
        Number($numberOfTreatments: intValue >= 1) from accumulate (
            SkinIssue(name == "Eczema" || name == "Psoriasis") from $treatedSkinIssues,
            count(1)
        )
        $response: TreatmentResponse()
    then
        System.out.println("Should prescribe antibiotics");
        insert(new DrugRecommendation(Drug.ANTIBIOTIC))

end

rule "Recommend Corticosteroids for eczema or psoriazis"
salience 4
activation-group "drug-recommendation"
    when
        SeriousSkinIssue(name == "Patient currently has eczema and/or psoriasis")
        Number($numberOfTreatments: intValue >= 2) from accumulate (
            Treatment(
                prescriptionDrug == Drug.ANTIBIOTIC,
                isIssueTreated("Eczema"),
                isIssueTreated("Psoriasis"))
            over window:time(180d),
            count(1)
        )
        $response: TreatmentResponse()
    then
        System.out.println("Should prescribe corticosteroids");
        insert(new DrugRecommendation(Drug.CORTICOSTEROID))
end

rule "Recommend Antifungal drug for blackheads or whiteheads"
salience 1
activation-group "drug-recommendation"
    when
        SeriousSkinIssue(name == "Patient currently has blackheads and/or whiteheads")
        $numberOfTreatments: Number(intValue >= 2) from accumulate (
            Treatment(
//                prescriptionDrug == Drug.NONE,
                isIssueTreated("Blackheads"),
                isIssueTreated("Whiteheads"))
            over window:time(120d),
            count(1)
        )
        $response: TreatmentResponse()
    then
        System.out.println("Should prescribe antifungal drug");
        insert(new DrugRecommendation(Drug.ANTIFUNGAL))
end

rule "Recommend Retinoids for acne"
salience 2
activation-group "drug-recommendation"
    when
        SeriousSkinIssue(name == "Patient currently has acne")
        $numberOfTreatments: Number(intValue >= 3) from accumulate (
            Treatment(
//                prescriptionDrug == Drug.NONE,
                isIssueTreated("Acne"))
            over window:time(240d),
            count(1)
        )
        $response: TreatmentResponse()
    then
        System.out.println("Should prescribe retinoids");
        insert(new DrugRecommendation(Drug.RETINOID))
end

query "getDrugRecommendation"
    DrugRecommendation($drug: drug)
end
